### ISSUE TITLE
Skip UUID field from seed

### ISSUE THREAD

**Issue by kshitij-enable** [jedymatt/sqlalchemyseed#59]
I have an UUID field in the models which is generated by postgres UUID extension. Is there any mechanism to skip adding the value for this field in the json file?  Error I am facing - 

Traceback (most recent call last):
  File "/Users/kshitij/enable/workspace/security/data/seed.py", line 19, in <module>
    seeder.seed(entities)
  File "/Users/kshitij/enable/workspace/security/.venv/lib/python3.11/site-packages/sqlalchemyseed/seeder.py", line 119, in seed
    self._pre_seed()
  File "/Users/kshitij/enable/workspace/security/.venv/lib/python3.11/site-packages/sqlalchemyseed/seeder.py", line 131, in _pre_seed
    self._seed()
  File "/Users/kshitij/enable/workspace/security/.venv/lib/python3.11/site-packages/sqlalchemyseed/seeder.py", line 166, in _seed
    init_item()
  File "/Users/kshitij/enable/workspace/security/.venv/lib/python3.11/site-packages/sqlalchemyseed/seeder.py", line 152, in init_item
    instance = class_(**filtered_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() missing 1 required positional argument: 'id'

**Comment by jedymatt** [comment]
@kshitij-enable thanks for reporting an issue. Can you provide a sample minimal model so that I can reproduce it in my end?

**Comment by jedymatt** [comment]
Seed data only passes the keys you provide to the model constructor — the library never requires all fields to be present. You can (and should) simply omit auto-generated columns like a UUID `id` from your JSON, and the database default (e.g. `gen_random_uuid()`) will fill it in.

The `TypeError: __init__() missing 1 required positional argument: 'id'` you saw comes from a **custom `__init__`** on your model that makes `id` mandatory — the default SQLAlchemy declarative constructor assigns keyword args and never raises this. To fix it on your side, either remove the custom `__init__`, give the column a Python-side/`server_default`, or let it be server-generated, and drop `id` from the seed JSON.

Closing as working-as-intended. Feel free to reopen if omitting the field still doesn't work with a standard declarative model.
